import { useState } from "react";
import { Lightbulb, TrendingUp, Users, Target, Brain, Award, AlertCircle, CheckCircle } from "lucide-react";

const recommendationsData = [
  {
    id: 1,
    userName: "E2E User",
    email: "e2e.1772577722@example.com",
    weakFinger: "left_pinky",
    suggestedDrill: "DL001",
    difficulty: "easy",
    confidence: 94.5,
    status: "Active",
    expectedImprovement: 12.3,
  },
  {
    id: 2,
    userName: "System Administrator",
    email: "admin@local.test",
    weakFinger: "right_ring",
    suggestedDrill: "DL015",
    difficulty: "medium",
    confidence: 89.2,
    status: "Completed",
    expectedImprovement: 8.7,
  },
  {
    id: 3,
    userName: "Demo User",
    email: "demo@ulus.tech",
    weakFinger: "left_middle",
    suggestedDrill: "DL008",
    difficulty: "easy",
    confidence: 96.8,
    status: "Active",
    expectedImprovement: 15.4,
  },
  {
    id: 4,
    userName: "E2E User",
    email: "e2e.1772574666@example.com",
    weakFinger: "right_pinky",
    suggestedDrill: "DL022",
    difficulty: "hard",
    confidence: 78.3,
    status: "Pending",
    expectedImprovement: 18.9,
  },
];

const mlInsights = [
  {
    title: "High-Impact Fingers",
    description: "Left pinky and right pinky show the most improvement potential",
    icon: Target,
    color: "text-blue-600",
    bgColor: "bg-blue-50",
  },
  {
    title: "Training Pattern",
    description: "Users perform best with 5-minute daily sessions",
    icon: TrendingUp,
    color: "text-emerald-600",
    bgColor: "bg-emerald-50",
  },
  {
    title: "Accuracy Trend",
    description: "Average accuracy increased by 7.2% this month",
    icon: Award,
    color: "text-purple-600",
    bgColor: "bg-purple-50",
  },
  {
    title: "ML Model Status",
    description: "Recommendation engine running at 92% confidence",
    icon: Brain,
    color: "text-amber-600",
    bgColor: "bg-amber-50",
  },
];

export function RecommendationAnalytics() {
  const [confidenceFilter, setConfidenceFilter] = useState("");
  const [statusFilter, setStatusFilter] = useState("");

  // Calculate statistics
  const totalRecommendations = recommendationsData.length;
  const activeRecommendations = recommendationsData.filter(r => r.status === "Active").length;
  const avgConfidence = (
    recommendationsData.reduce((sum, rec) => sum + rec.confidence, 0) / totalRecommendations
  ).toFixed(1);
  const avgImprovement = (
    recommendationsData.reduce((sum, rec) => sum + rec.expectedImprovement, 0) / totalRecommendations
  ).toFixed(1);

  return (
    <div>
      {/* Page Header */}
      <div className="mb-6">
        <div className="flex items-center gap-3 mb-2">
          <Lightbulb className="w-6 h-6 text-blue-600" />
          <h1 className="text-2xl font-semibold text-slate-800">Recommendation Analytics</h1>
        </div>
        <p className="text-slate-500">ML-powered personalized training recommendations and insights</p>
      </div>

      {/* Statistics Cards */}
      <div className="grid grid-cols-4 gap-6 mb-6">
        <div className="bg-white rounded-xl p-6 shadow-sm border border-slate-100">
          <div className="flex items-center justify-between mb-3">
            <p className="text-sm text-slate-500">Total Recommendations</p>
            <Lightbulb className="w-5 h-5 text-blue-500" />
          </div>
          <p className="text-3xl font-bold text-slate-800">{totalRecommendations}</p>
          <p className="text-xs text-slate-400 mt-2">Generated by ML</p>
        </div>

        <div className="bg-white rounded-xl p-6 shadow-sm border border-slate-100">
          <div className="flex items-center justify-between mb-3">
            <p className="text-sm text-slate-500">Active</p>
            <Users className="w-5 h-5 text-emerald-500" />
          </div>
          <p className="text-3xl font-bold text-slate-800">{activeRecommendations}</p>
          <p className="text-xs text-slate-400 mt-2">In progress</p>
        </div>

        <div className="bg-white rounded-xl p-6 shadow-sm border border-slate-100">
          <div className="flex items-center justify-between mb-3">
            <p className="text-sm text-slate-500">Avg Confidence</p>
            <Brain className="w-5 h-5 text-purple-500" />
          </div>
          <p className="text-3xl font-bold text-slate-800">{avgConfidence}%</p>
          <p className="text-xs text-slate-400 mt-2">Model accuracy</p>
        </div>

        <div className="bg-white rounded-xl p-6 shadow-sm border border-slate-100">
          <div className="flex items-center justify-between mb-3">
            <p className="text-sm text-slate-500">Avg Improvement</p>
            <TrendingUp className="w-5 h-5 text-amber-500" />
          </div>
          <p className="text-3xl font-bold text-slate-800">{avgImprovement}%</p>
          <p className="text-xs text-slate-400 mt-2">Expected gain</p>
        </div>
      </div>

      {/* ML Insights Cards */}
      <div className="grid grid-cols-2 gap-6 mb-6">
        {mlInsights.map((insight) => {
          const Icon = insight.icon;
          return (
            <div key={insight.title} className="bg-white rounded-xl p-6 shadow-sm border border-slate-100">
              <div className="flex items-start gap-4">
                <div className={`w-12 h-12 rounded-lg ${insight.bgColor} flex items-center justify-center flex-shrink-0`}>
                  <Icon className={`w-6 h-6 ${insight.color}`} />
                </div>
                <div>
                  <h3 className="font-semibold text-slate-800 mb-1">{insight.title}</h3>
                  <p className="text-sm text-slate-600">{insight.description}</p>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {/* Filter Bar */}
      <div className="bg-white rounded-xl p-6 shadow-sm border border-slate-100 mb-6">
        <div className="flex items-center gap-4">
          <div className="flex-1">
            <label className="block text-sm text-slate-600 mb-2">Minimum Confidence</label>
            <select
              value={confidenceFilter}
              onChange={(e) => setConfidenceFilter(e.target.value)}
              className="w-full px-4 py-2.5 border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/50"
            >
              <option value="">All Confidence Levels</option>
              <option value="90">90%+ (High)</option>
              <option value="80">80%+ (Medium)</option>
              <option value="70">70%+ (Low)</option>
            </select>
          </div>

          <div className="flex-1">
            <label className="block text-sm text-slate-600 mb-2">Status</label>
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              className="w-full px-4 py-2.5 border border-slate-200 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/50"
            >
              <option value="">All Status</option>
              <option value="Active">Active</option>
              <option value="Completed">Completed</option>
              <option value="Pending">Pending</option>
            </select>
          </div>

          <div className="flex-1">
            <label className="block text-sm text-slate-600 mb-2">&nbsp;</label>
            <button className="w-full px-4 py-2.5 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors">
              Apply Filters
            </button>
          </div>
        </div>
      </div>

      {/* Recommendations Table */}
      <div className="bg-white rounded-xl shadow-sm border border-slate-100 overflow-hidden">
        <div className="px-6 py-4 border-b border-slate-100 bg-gradient-to-r from-blue-50 to-purple-50">
          <div className="flex items-center gap-2">
            <Brain className="w-5 h-5 text-blue-600" />
            <h2 className="text-lg font-semibold text-slate-800">ML-Generated Recommendations</h2>
          </div>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="bg-slate-50 border-b border-slate-100">
                <th className="text-left px-6 py-4 text-sm font-medium text-slate-600">User</th>
                <th className="text-left px-6 py-4 text-sm font-medium text-slate-600">Email</th>
                <th className="text-left px-6 py-4 text-sm font-medium text-slate-600">Weak Finger</th>
                <th className="text-left px-6 py-4 text-sm font-medium text-slate-600">Suggested Drill</th>
                <th className="text-left px-6 py-4 text-sm font-medium text-slate-600">Difficulty</th>
                <th className="text-left px-6 py-4 text-sm font-medium text-slate-600">ML Confidence</th>
                <th className="text-left px-6 py-4 text-sm font-medium text-slate-600">Expected Gain</th>
                <th className="text-left px-6 py-4 text-sm font-medium text-slate-600">Status</th>
              </tr>
            </thead>
            <tbody>
              {recommendationsData.map((rec, index) => (
                <tr
                  key={rec.id}
                  className={`border-b border-slate-100 last:border-0 hover:bg-slate-50 transition-colors ${
                    index % 2 === 0 ? "bg-white" : "bg-slate-50/50"
                  }`}
                >
                  <td className="px-6 py-4 text-sm text-slate-800">{rec.userName}</td>
                  <td className="px-6 py-4 text-sm text-slate-600">{rec.email}</td>
                  <td className="px-6 py-4 text-sm text-slate-800">{rec.weakFinger}</td>
                  <td className="px-6 py-4">
                    <span className="text-sm font-medium text-blue-600">{rec.suggestedDrill}</span>
                  </td>
                  <td className="px-6 py-4">
                    <span
                      className={`px-3 py-1 rounded-full text-xs font-medium ${
                        rec.difficulty === "easy"
                          ? "bg-emerald-100 text-emerald-700"
                          : rec.difficulty === "medium"
                          ? "bg-amber-100 text-amber-700"
                          : "bg-red-100 text-red-700"
                      }`}
                    >
                      {rec.difficulty}
                    </span>
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-2">
                      <div className="flex-1 bg-slate-200 rounded-full h-2 overflow-hidden max-w-[100px]">
                        <div
                          className={`h-full ${
                            rec.confidence >= 90
                              ? "bg-emerald-500"
                              : rec.confidence >= 80
                              ? "bg-blue-500"
                              : "bg-amber-500"
                          }`}
                          style={{ width: `${rec.confidence}%` }}
                        ></div>
                      </div>
                      <span
                        className={`text-sm font-medium ${
                          rec.confidence >= 90
                            ? "text-emerald-600"
                            : rec.confidence >= 80
                            ? "text-blue-600"
                            : "text-amber-600"
                        }`}
                      >
                        {rec.confidence}%
                      </span>
                    </div>
                  </td>
                  <td className="px-6 py-4">
                    <span className="text-sm font-medium text-emerald-600">+{rec.expectedImprovement}%</span>
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-2">
                      {rec.status === "Active" && (
                        <>
                          <AlertCircle className="w-4 h-4 text-blue-500" />
                          <span className="text-sm text-blue-700">Active</span>
                        </>
                      )}
                      {rec.status === "Completed" && (
                        <>
                          <CheckCircle className="w-4 h-4 text-emerald-500" />
                          <span className="text-sm text-emerald-700">Completed</span>
                        </>
                      )}
                      {rec.status === "Pending" && (
                        <>
                          <AlertCircle className="w-4 h-4 text-amber-500" />
                          <span className="text-sm text-amber-700">Pending</span>
                        </>
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
